# Generated by Django 2.2.1 on 2019-06-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190614_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='description',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, verbose_name='Conteudo'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.Course', verbose_name='Curso'),
        ),
    ]
