# Generated by Django 2.2.1 on 2019-06-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190617_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='nome',
            new_name='name',
        ),
    ]
