# Generated by Django 2.2.1 on 2019-06-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190617_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='nome',
            new_name='name',
        ),
    ]
