# Generated by Django 2.2.1 on 2019-06-06 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordreset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nova Senha', 'verbose_name_plural': 'Novas Senhas'},
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Confirmado?'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
